### ISSUE TITLE
Linking failed

### ISSUE THREAD

**Issue by qkdreyer** [thejustinwalsh/heaps-ios#1]
`
Ld /Users/qkdreyer/Projects/heaps-ios/build/build/products/Debug-iphonesimulator/HeapsApp.app/HeapsApp normal x86_64 (in target 'HeapsApp' from project 'HeapsApp')
    cd /Users/qkdreyer/Projects/heaps-ios/build
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios12.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk -L/Users/qkdreyer/Projects/heaps-ios/build/build/products/Debug-iphonesimulator -L/Users/qkdreyer/Projects/heaps-ios/build/deps/turbojpeg/dependencies-lib/lib -L/Users/qkdreyer/Projects/heaps-ios/build/deps/hashlink -F/Users/qkdreyer/Projects/heaps-ios/build/build/products/Debug-iphonesimulator -F/Users/qkdreyer/Projects/heaps-ios/build/deps/IDZPrecompiledOgg -F/Users/qkdreyer/Projects/heaps-ios/build/deps/IDZPrecompiledVorbis -filelist /Users/qkdreyer/Projects/heaps-ios/build/build/intermediates/HeapsApp.build/Debug-iphonesimulator/HeapsApp.build/Objects-normal/x86_64/HeapsApp.LinkFileList -dead_strip -Xlinker -object_path_lto -Xlinker /Users/qkdreyer/Projects/heaps-ios/build/build/intermediates/HeapsApp.build/Debug-iphonesimulator/HeapsApp.build/Objects-normal/x86_64/HeapsApp_lto.o -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/qkdreyer/Projects/heaps-ios/build/build/intermediates/HeapsApp.build/Debug-iphonesimulator/HeapsApp.build/HeapsApp.app-Simulated.xcent /Users/qkdreyer/Projects/heaps-ios/build/build/products/Debug-iphonesimulator/libSDL2.a -lturbojpeg -ljpeg -framework Ogg -framework Vorbis -lsqlite3 -lz -framework MetalKit -framework Metal -framework AVFoundation -framework GameController -framework Foundation -framework UIKit -framework OpenAL -framework OpenGLES -framework QuartzCore -framework CoreAudio -framework AudioToolbox -framework CoreGraphics -framework CoreMotion -Xlinker -dependency_info -Xlinker /Users/qkdreyer/Projects/heaps-ios/build/build/intermediates/HeapsApp.build/Debug-iphonesimulator/HeapsApp.build/Objects-normal/x86_64/HeapsApp_dependency_info.dat -o /Users/qkdreyer/Projects/heaps-ios/build/build/products/Debug-iphonesimulator/HeapsApp.app/HeapsApp
`

```
Undefined symbols for architecture x86_64:
  "_fmt_dxt_decode", referenced from:
      _hxd_Pixels_convert in HeapsApp.o
      _hl_functions_ptrs in HeapsApp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by thejustinwalsh** [comment]
Good luck! I will no longer be maintaining this project. I can transfer the repo to whomever wants to maintain it.

**Comment by qkdreyer** [comment]
Fixed it using https://gist.githubusercontent.com/qkdreyer/54245f242ce69d61bd4816e135dcb930/raw/e6392463adfa438110d06a0d65c289009c73400a/gistfile1.txt as workaround using hashlink 1.10
